# -*- coding: utf-8 -*-
"""sandhi_telugu

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UlpjMIVPgRXXUxTZffe8EyGBCDvnofW2
"""

# from google.colab import drive
# drive.mount('/content/gdrive')

master_list  = []
import re

with open('telugu.syns') as reader:
  count = 0
  for line in reader.readlines():
    words = line.split()
    if(len(words)>1):
      master_list.extend(words[2:-1])

f = []
s = []
test = []
with open('dataset.txt') as reader:
  for line in reader.readlines():
    words = line.split(',')
    f.append(words[0])
    s.append(words[1])
    test.append(words[2])



for i in range(len(master_list)):
  master_list[i]=re.sub('\"','',master_list[i])

# master_list[:100]

# text_input='కాకికీకుకూకృకౄకెకేకైకొకోకౌకంకః'
# text_input = 'ఆర్య'
# code=[]
# for i  in range(len(text_input)):
#   if(i%2!=0):
#     print(text_input[i])



sandhi_dict = {}
sandhi_dict['ా'] = [['','ఆ'],['','అ'],['ా','ఆ'],['ా','అ']]  #savarna deerga sandhi
sandhi_dict['ి'] = [['ి','అ']]  #ekara sandi
sandhi_dict['ీ'] = [['ి','ఇ'],['ి','ఈ'],['ీ','ఇ'],['ీ','ఈ']]
sandhi_dict['ు'] = [['ు','అ']]  #ukaara sandi
sandhi_dict['ూ'] = [['ు','ఉ'],['ు','ఊ'],['ూ','ఉ'],['ూ','ఊ']]
sandhi_dict['ౄ'] = [['ృ','ఋ'],['ృ','ౠ'],['ౄ','ఋ'],['ౄ','ౠ']] 
sandhi_dict['ే'] = [['','ఈ']]
sandhi_dict['ై'] = [['','ఓ'],['','ఔ']]
sandhi_dict['ో'] = [['','ఉ']]
sandhi_dict['ౌ'] = [['','ఓ'],['','ఔ']]
sandhi_dict['ర'+ '్'] = [['','ఋ']]
# anunaasika sandhi
sandhi_dict['ఙ'] = [['క'+'్','న'],['క'+'్','మ']]
sandhi_dict['ఞ'] = [['చ'+'్','న'],['చ'+'్','మ']]
sandhi_dict['ణ'] = [['ట'+'్','న'],['ట'+'్','మ']]
sandhi_dict['న'] = [['త'+'్','న'],['త'+'్','మ']]
sandhi_dict['మ'] = [['ప'+'్','న'],['ప'+'్','మ']]
# yaanadesa sandhi
sandhi_dict['య'] = [['ి','అ']]
sandhi_dict['యా'] = [['ి','ఆ']]
sandhi_dict['యు'] = [['ి','ఉ']]
sandhi_dict['యూ'] = [['ి','ఊ']]
sandhi_dict['వ'] = [['ు','అ']]
sandhi_dict['వా'] = [['ు','ఆ']]
sandhi_dict['వి'] = [['ు','ఇ']]
sandhi_dict['వీ'] = [['ు','ఈ']]
sandhi_dict['ర'] = [['ృ','అ']]
sandhi_dict['రా'] = [['ృ','ఆ']]
sandhi_dict['రి'] = [['ృ','ఇ']]
sandhi_dict['రీ'] = [['ృ','ఈ']]
sandhi_dict['రు'] = [['ృ','ఉ']]
sandhi_dict['రూ'] = [['ృ','ఊ']]
# akara sandhi ki rayali 
sandhi_dict['క'] = [['క','అ']]
sandhi_dict['ఖ'] = [['ఖ','అ']]
sandhi_dict['గ'] = [['గ','అ']]
sandhi_dict['ఘ'] = [['ఘ','అ']]
sandhi_dict['చ'] = [['చ','అ']]
sandhi_dict['ఛ'] = [['ఛ','అ']]
sandhi_dict['జ'] = [['జ','అ']]
sandhi_dict['ఝ'] = [['ఝ','అ']]
sandhi_dict['ట'] = [['ట','అ']]
sandhi_dict['ఠ'] = [['ఠ','అ']]
sandhi_dict['డ'] = [['డ','అ']]
sandhi_dict['ఢ'] = [['ఢ','అ']]
sandhi_dict['త'] = [['త','అ']]
sandhi_dict['థ'] = [['థ','అ']]
sandhi_dict['ద'] = [['ద','అ']]
sandhi_dict['ధ'] = [['ధ','అ']]
sandhi_dict['ప'] = [['ప','అ']]
sandhi_dict['ఫ'] = [['ఫ','అ']]
sandhi_dict['బ'] = [['బ','అ']]
sandhi_dict['భ'] = [['భ','అ']]
# time vunte visarga sandhi rayali



text_input="రాణ్మణి"

# for char in sandhi_dict.keys():
#   temp=re.split(char,text_input)
#   if(len(temp)>1):
#     print(temp)
#     temp_list=sandhi_dict[char]
#     print(temp_list)





def fun(text_input):
  final_answer=[]
  for char in sandhi_dict.keys():
    temp=re.split(char,text_input)
    if(len(temp)>1):
      temp_list = sandhi_dict[char]
      for x in temp_list:
        first = temp[0]+x[0]
        second = x[1]+temp[1]
        print(first,second)
        if(first in master_list and second in master_list):
          if(char=='ఙ' or char=='ఞ' or char=='ణ' or char=='న' or char=='మ'):
            if((temp[1][0]=='మ' or temp[1][0]=='న')):
              final_answer.append([first,second])
          else:
              final_answer.append([first,second])
        if(char=='య' or char=='యా' or char=='యు' or char=='యూ' or char=='వ' or char=='వా' or char=='వి' or char=='వీ' or char=='ర' or char=='రా' or char=='రి' or char=='రీ' or char=='రు' or char=='రూ'):
          temp[0] = re.sub('్','',temp[0])
          first=temp[0]+x[0]
          second=x[1]+temp[1]
          print(first,second,"hi")
          if(first in master_list and second in master_list):
            final_answer.append([first,second])
  print(final_answer)

# for i  in range(len(text_input)):
#   print(text_input[i])

# for char in sandhi_dict.keys():
# temp=re.split('ా',text_input)
# print(temp)

for x in test:
  fun(x)

